from enums import Vehicle, Condition

VEHICLE_MOTORCYCLE = 'MOTOR'
VEHICLE_CAR = 'MOBIL'

CONDITION_USED = 'BEKAS'
CONDITION_NEW = 'BARU'

YEAR_FORMAT = 'YYYY'

VEHICLE_MAP = {VEHICLE_MOTORCYCLE: Vehicle.MOTORCYCLE, VEHICLE_CAR: Vehicle.CAR}
CONDITION_MAP = {CONDITION_USED: Condition.USED, CONDITION_NEW: Condition.NEW}

